### ISSUE TITLE
Bugs that I have found so far in RC1

### ISSUE THREAD

**Issue by cheuklam** [ecnepsnai/Lucy#13]
Hey folks,

Thank you very much for creating this light and easy to use ticketing system. I would say this is by far the best light-weight ticketing system I saw in opensource community. I am done with those complicated one as I just want something simple and issue for me and my client.

Anyway, after testing for several hours, I found quite a number of bugs here.
1) in forgot password, wrong spelling "S new password", should be "A new password"
2) for the verification link, you wrongly make it "email_erifiy.php", miss the "v" in the a href.
3) lucy-content/uploads is not included in the branch / master or any zip / tar files
4) some file in the setup script no longer required, please take them out.
5) Now, even I set the email in the setting page, it is still using your personal email. I need to update it manually in mailer.php
6) Typo and grammer mistake in many warning / alert. I didn't go through everything 1 by 1, just edit it when I see it.

+Oil, this is very close to what I want! I am sure many ppl will find it very easy to use.

P.S. May I know why it is call Lucy, is she your dream girl xp?

**Comment by ecnepsnai** [comment]
Hi @cheuklam.

Thanks for the bug list.  Lucy has been abandoned for quite some time now.  If you're interested, feel free to take over.  I have no plans nor interest in continuing work on Lucy.

Best.
